### PR TITLE
Fixing Python turing machine

### PR DESCRIPTION
**Pull request by lennart-k**
I've made some mistakes in #﻿284 and forgot to test it after the last change.
Now it should work :)

### CODE REVIEW

**Comment by NLDev** [comment]
perfect! thanks :)

**Comment by NLDev** [comment]
Quick question? Might if I link your solution under the top 10 solutions in the readme?

**Comment by lennart-k** [comment]
Of course, I'd be happy about that :)

**Comment by NLDev** [comment]
Awesome! added :)

**Pull request merged**
