### PR TITLE
Java fix

### LINKED ISSUE #524: Most of the Java code does not work
With my current setup (JDK 11 + VS Code or GitHub Codespaces) I am unable to test most of the Java code in this repo. Here are some problematic code snippets:

- Use of JUnit
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/076e35dc89ae91dfe3def5e7a90b960d7c5ac558/Java/FizBuzzTDD.java#L1-L7
- Import statements inside class body
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/076e35dc89ae91dfe3def5e7a90b960d7c5ac558/Java/AFL_FizzBuzz_FirstTDD.java#L56-L59
- File name != public class name
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/076e35dc89ae91dfe3def5e7a90b960d7c5ac558/Java/FizzBuzz%20-Main_Ternary_Operator.java#L6
- Import statements for `List` / `ArrayList` missing
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/076e35dc89ae91dfe3def5e7a90b960d7c5ac558/Java/fizbuzz-for.java#L4
- CSV not found
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/076e35dc89ae91dfe3def5e7a90b960d7c5ac558/Java/PseudoRandomFizzBuzz.java#L16

- Some contributors also forgot to add the first comment lines, i. e. a short description and credit.

If you want this issue fixed, @NLDev, assign me this issue and I'll be happy to fix it.

### PR DESCRIPTION
**Pull request by pr1metine**
Fixes #524. The TDD entries are taken care of in a seperate PR.

### CODE REVIEW

**Comment by tobi6112** [comment]
Good Job, but why do you rename most of the classes in contradiction to the Java Code Conventions? https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

**Comment by pr1metine** [comment]
Ik, @tobi6112.

Do you mean the underscores?

**Comment by tobi6112** [comment]
> Ik, @tobi6112.
> 
> Do you mean the underscores?

Yeah, exactly.

**Comment by pr1metine** [comment]
I, too, adhere to said Convention and exclusively use PascalCase for class names. Sonarlint already warned me about this.

Nonetheless, I decided to separate the names with `_` for improved readability. Otherwise, class names would have ended up like `FizzBuzzPseudoRandomCSVGen` as opposed to 
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/ab0f3d609fbdfb89bcdcc2fcf3f19dc521bff336/Java/FizzBuzz_PseudoRandomCSVGen.java#L10
(and I, like many others, really wanted to keep `FizzBuzz` in the title).

**Comment by NLDev** [comment]
Awesome! Thanks you :D

**Comment by pr1metine** [comment]
I thank you too, @NLDev, for merging all of my PRs! 😄

If you need a co-maintainer who reviews PRs and checks them for mistakes, I will gladly help you with this.

**Comment by NLDev** [comment]
Hey! Thank you for the offer :D 
That would be pretty cool I guess but I'm not sure whether that'll work out or if it leads to mistakes. 
I enforce a certain set of rules that determine if a PR should be merged or closed. Sometimes I'm even uncertain myself :/

**Pull request merged**
