### PR TITLE
AddedSQL

### PR DESCRIPTION
**Pull request by GauravPoosarla**
This is a SQL code for FizzBuzz

### CODE REVIEW

**Comment by NLDev** [comment]
Neat! Thank you :D

**Comment by GauravPoosarla** [comment]
I forgot to add my name as author, is it fine?

**Comment by NLDev** [comment]
Ill do it for you ^^

**Comment by GauravPoosarla** [comment]
Thanks similarly i forgot to add my name in python as well, the pull request there was #172

**Comment by NLDev** [comment]
Added!

**Pull request merged**
