### PR TITLE
FizzBuzz in Python

### PR DESCRIPTION
**Pull request by Hinal-Srivastava**
FizzBuzz problem is solved using functions.

### CODE REVIEW

**Comment by Hinal-Srivastava** [comment]
@NLDev I came up with this on my own as you suggested. Earlier it was the first contribution so I didn't know how to check other files😅

**Comment by NLDev** [comment]
Interesting! Thank you :D

**Comment by Hinal-Srivastava** [comment]
> Interesting! Thank you :D

Great! Thanks😁

**Comment by Hinal-Srivastava** [comment]
@NLDev would be really great if you added the `hacktobefest-accepted` label! 🙂

**Comment by NLDev** [comment]
No need. That would be redundant. 

The hacktoberfest websites states that all PR's count, that are either **merged or approved** on a repository with the "hacktoberfest" tag (which is the case on this repository) OR _any_ PR that was labeled with `hacktoberfest-accepted` (either on participating repositories or a non-hacktoberfest repository)

Check your profile on https://hacktoberfest.digitalocean.com/profile
The PR should already be there.

**Pull request merged**
