### PR TITLE
Create basic_FizzBuzz.java

### PR DESCRIPTION
**Pull request by rakshit234**

### CODE REVIEW

**Comment by NLDev** [comment]
Thank you for your PR!
Unfortunately a solution similar to yours has already been submitted :/ 
The goal is to find creative/abstract new solutions to FizzBuzz. 
See [The top 5 samples here](https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz#trophy-top-5-personal-favorites).
Thanks anyway! :)

**Comment by rakshit234** [comment]
Hi, can you please open it? I will add a different code.

**Comment by rakshit234** [comment]
import java.util.*;
public class Solution {
    public static void main(String[] args) {
        Scanner s = new Scanner(System.in);
        int n = s.nextInt();
        int i=1;
        while(i<=n){
            String str;
            if(i % (15) == 0){
                str = "FizzBuzz";
            }else if(i % 3 == 0){
                str = "Fizz";
            }else if(i % 5 == 0){
                str = "Buzz";
            }else
                str = Integer.toString(i);
            System.out.println(str);
            i++;
        }
    }
}

Is this a valid code according to the repository? I have used while loop in this code and no java code in your repo use while loop. Please reply..

**Comment by NLDev** [comment]
No, sorry. Please consult the readme. This is still a standard approach to FizzBuzz. We search Creative/Extraordinary solutions. 
Not normal standard solutions with different methodologies

**Pull request closed without merging**
