### PR TITLE
Create sliding_window.py

### PR DESCRIPTION
**Pull request by deadshotsb**
#3 

This program uses sliding window algorithm and modulo operator to detect fizzbuzz, fizz and buzz numbers.

### CODE REVIEW

**Comment by NLDev** [comment]
neat! thx :)

**Comment by deadshotsb** [comment]
@NLDev  Welcome, can you add a Hacktoberfest label to this pull. As a contributor i cannot update the label.

**Comment by NLDev** [comment]
This repository is already labeled with the 'hacktoberfest' tag. Individual PR's don't need this label. They automatically count if they have been merged, approved or labled as "hacktoberfest-accepted". Since I merged this PR, no further action is required. 

Cheers

**Comment by deadshotsb** [comment]
Thanks for that.

Cheers mate.

**Pull request merged**
