### PR TITLE
CPP Solution

### PR DESCRIPTION
**Pull request by BreathlessVictor**
This is the basic C++ solution to the FizzBuzz program

### CODE REVIEW

**Comment by BreathlessVictor** [comment]
I added this PR when the C++ folder was not present. I would like to add this to the C++ folder.

**Comment by BreathlessVictor** [comment]
Thanks for replying. 
Cheers!

**Comment by NLDev** [comment]
Quick update on that one: Unfortunately due to change of policy I have to mark duplicated solutions as invalid :/
Sorry about that. Feel free to submit a new PR tho!

**Comment by BreathlessVictor** [comment]
I understand but sir if you see the timeline, I was the first person to submit the C++ solution. Please consider if possible. Thanks.

**Comment by NLDev** [comment]
Unfortunately you weren't. I work through all PR's from oldest to newest. I reviewed a total of 264 PR's yesterday with this system and not a single mistake has happened so far. I just checked the C++ code solutions and one solution was committed at October 1st 10:59 [(source)](https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/master/C%2B%2B/fizzzbuzz-1.cpp) while your PR was created at October 1st 11:11.

In addition to that: The ReadMe as well as the issue states that we search for creative/extraordinary solutions to FizzBuzz, just like [the Top 5 solutions](https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz#trophy-top-5-personal-favorites). For the sake of completeness we allow one "normal" solution per language. You were the second one who submitted a standard C++ solution which is why I closed this PR. 

Cheers

**Pull request closed without merging**
