### PR TITLE
small typo fix

### PR DESCRIPTION
**Pull request by muhazafasa**
Just one more small contribution, not even supposed to count in Hacktoberfest :)

### CODE REVIEW

**Comment by muhazafasa** [comment]
Oh, it seems like there are no way to merge PR and not count it. So I can offer you to reject it and fix it by you own.

**Comment by NLDev** [comment]
> Oh, it seems like there are no way to merge PR and not count it. So I can offer you to reject it and fix it by your own.

What do you mean?

**Comment by muhazafasa** [comment]
Nevermind, I thought that such a pure PR seems like a joke and you would mark it invalid :D

**Comment by NLDev** [comment]
Eh, it's fine. According to hacktoberfest, one PR to fix a typo is okay :) 
Don't worry about it. This contribution is more valuable than the 200 PR's I've marked as invalid because they were just copy-paste solutions ^^

**Pull request merged**
