### PR TITLE
99BottlesOfBeer Poem just in 7 line in python

### PR DESCRIPTION
**Pull request by pktintali**

### CODE REVIEW

**Comment by pktintali** [comment]
Sorry By Mistake :(

**Comment by pktintali** [comment]
Opened

**Comment by NLDev** [comment]
Thanks, but this repo is about FizzBuzz ^^
Ill close this PR now. Don't worry, it still counts!

**Comment by pktintali** [comment]
> Thanks, but this repo is about FizzBuzz ^^

Actually I did that Accidentally

**Comment by NLDev** [comment]
No worries :)

**Pull request closed without merging**
