### PR TITLE
Nim Compile-time using a macro

### PR DESCRIPTION
**Pull request by Tuatarian**

### CODE REVIEW

**Comment by Tuatarian** [comment]
@NLDev Don't know if you can edit the PR before merging, and it isn;t a huge deal, but I accidently left in a debugging command `i.treeRepr` which was in there so I could see the AST node for I and figure out how to cast to an intval. It's not a hueg deal, this will compile & run & do what it needs to, but yeah

**Comment by NLDev** [comment]
Aight! Yea I can checkout this PR as branch and remove it. Is the binary file needed as well? Because we usually only merge scripts. not binaries

**Comment by NLDev** [comment]
Done! I removed the binary as well. Just let me know if its needed. Ill merge now :)

**Comment by Tuatarian** [comment]
binary isn't needed, just compiler residue :)

**Pull request merged**
