### PR TITLE
Added elixir code

### PR DESCRIPTION
**Pull request by GauravPoosarla**
Is this fine?

### CODE REVIEW

**Comment by NLDev** [comment]
I think a solution like has already been submitted :/ 
Please check https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/tree/master/Elixir to see if it's a duplicate. 

Keep in mind: The goal is to find creative/abstract new solutions to FizzBuzz. Not normal standard solutions.
See [The top 5 samples here](https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz#trophy-top-5-personal-favorites).

Cheers!

**Comment by GauravPoosarla** [comment]
Ok that's why i sent a draft, i will close this request, sorry I will try another method.

**Comment by NLDev** [comment]
aight!

**Comment by GauravPoosarla** [comment]
can you now check once?

**Comment by GauravPoosarla** [comment]
I am learning this language xD

**Comment by NLDev** [comment]
yep! merging now :)

**Comment by GauravPoosarla** [comment]
Thanks :)

**Comment by GauravPoosarla** [comment]
Forgot to add my name as author, it is fine right?

**Comment by NLDev** [comment]
Added it for you: 
https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/master/Elixir/FizzBuzz.ex#L1

**Comment by GauravPoosarla** [comment]
Thanks!

**Pull request merged**
