### PR TITLE
HuffMan Coding In Java

### PR DESCRIPTION
**Pull request by AryashDubey**

### CODE REVIEW

**Comment by NLDev** [comment]
This is nice and all except that the code has nothing to do with FizzBuzz and is copy-pasted [from StackOverflow](https://stackoverflow.com/questions/40752811/how-can-i-make-this-huffman-project-read-from-file).

**Comment by Tuatarian** [comment]
Man, these kinds of PRs are confusing

**Comment by NLDev** [comment]
@Tuatarian What do you mean?

**Comment by Tuatarian** [comment]
It has no relation to fizzbuzz or anything really

**Comment by NLDev** [comment]
I got a lot of such PR's. Fibonacci sequence, String reversals, all that kind of stuff... People just want a Hacktoberfest PR and don't even bother reading the ReadMe

**Pull request closed without merging**
