### PR TITLE
Readme file update with visual explanation

### PR DESCRIPTION
**Pull request by hardword**
Readme file update with visual explanation

### CODE REVIEW

**Comment by NLDev** [comment]
Thanks for the picture! But I'm not quite happy with the formatting just yet... 
If you add it like that to your PR, ill merge it: 

```html
<p align="center">
<img height="300" width="auto" src="https://64.media.tumblr.com/098171eb6557f68cae65fdffe485abc4/tumblr_onha88HP0a1w0dccho1_1280.gif"><br>
  <sub><a href="https://100daysofalgorithms.tumblr.com/post/158891499866/day-86-ode-to-fizzbuzz-fizzbuzz-is-the-simplest">[Image source © 100daysofalgorithms]</a></sub>
</p>
```

cheers!

**Comment by NLDev** [comment]
Perfect! Thank you :)

**Comment by hardword** [comment]
@NLDev 
Thanks for the feedback. I updated the pull request as you requested.

**Comment by NLDev** [comment]
Already merged :)

**Pull request merged**
