### PR TITLE
Created a simple Fizzbuzz code in Javascript

### PR DESCRIPTION
**Pull request by flyinspaghetti**
A simple fizzbuzz code in Javascript using a for loop and if statements.

### CODE REVIEW

**Comment by NLDev** [comment]
thx!

**Comment by flyinspaghetti** [comment]
> thx!

Hello, can you please mark my submission with the hacktoberfest tag?
It's showing me that that repository is ineligible because there is no hacktoberfest tag.

Here is what it says from their website: 
"Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR."

**Comment by NLDev** [comment]
This repository has the hacktoberfest topic and PR's to it seem to be just fine. Mind including a screenshot?

**Comment by flyinspaghetti** [comment]
My apologies. That was another repository, therefore I deleted my comment. This repository is fine. 
Sorry for the inconvenience.

**Pull request merged**
