### PR TITLE
A different approach to fizzbuzz program

### PR DESCRIPTION
**Pull request by vighneshdeepweb**
Contribution to Hacktoberfest2020 review it and give ur valuable suggestions/advices.Thank You

### CODE REVIEW

**Comment by NLDev** [comment]
Thanks!

**Comment by vighneshdeepweb** [comment]
welcome

**Comment by vighneshdeepweb** [comment]
is this merge hacktober accepted?? @NLDev

**Comment by NLDev** [comment]
Yea it should be. You can check the status on your profile: https://hacktoberfest.digitalocean.com/profile

**Comment by vighneshdeepweb** [comment]
So can u put a label of hacktober fest accepted in this merge....

**Comment by NLDev** [comment]
Haven't you checked your profile? The PR should already be there. Read the docs on the website of hacktoberfest. This repository has the hacktoberfest tag.Thus, all PR's that are **accepted** and do not **have the invalid/spam** label, are accepted. Adding a label to this PR is redundant. The fact that you asked three times for that shows that you don't really care about contributing to open source by the way... Your solution isn't even that unique/creative. Might as well delete the submission and label this PR as invalid.

**Comment by vighneshdeepweb** [comment]
So sorry sir I did not want to make u angry it was honestly my first time open source contribution event I have understood completely sry sir really sorry for my stupid behaviour and from next time i will keep this is my mind so sry sir pls forgive me this time.....

**Pull request merged**
