### PR TITLE
FizzBuzz implementation in Piet

### PR DESCRIPTION
**Pull request by muhazafasa**

### CODE REVIEW

**Comment by NLDev** [comment]
Very interesting! thank you :)
could you provide more information on how you made that and how it's interpreted?

**Comment by muhazafasa** [comment]
Hi there!
First of all, thank you for creating such an interesting idea for Hacktoberfest repo, which is simple and complex at the same time :)
What about Piet - I really enjoy this language (just language, not coding :D), especially how it looks like. I learnt about it when I was at the university, it was really fun to get acquainted with plenty of esoteric programming languages. And when BrainFuck and Whitespace are mainstream, Piet was a real discover for me.
The main idea of it is really simple. It provides a set of assembler-like instructions, so all you have to do is to code it like in Assembly and after that parse it into the image (every instruction has its own set of pixels).
Here you can find more: https://www.dangermouse.net/esoteric/piet.html

**Comment by NLDev** [comment]
Awesome! Thank you for the info :D 
Mind if I link your comment in the code?

**Comment by muhazafasa** [comment]
Yeah, sure, that’s fine

**Pull request merged**
